<?php
/**
 * @file
 * Etherpad lite integration for Drupal.
 *
 * Main concept: Etherpad as a field.
 */

/**
 * Implements hook_menu().
 */
function etherpad_lite_menu() {
  $items = array();

  $items['admin/config/services/etherpad-lite'] = array(
    'title' => 'Etherpad lite',
    'description' => 'Configure Etherpad lite.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('etherpad_lite_admin_settings'),
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

function etherpad_lite_admin_settings() {
  $form = array();

  $form['etherpad_lite_apikey'] = array(
    '#type' => 'textfield',
    '#title' => 'Etherpad API Key',
    '#default_value' => variable_get('etherpad_lite_apikey'),
    '#required' => TRUE,
    '#description' => 'Serach for APIKEY.txt in your Etherpad Lite installation.',
  );

  $form['etherpad_lite_url'] = array(
    '#type' => 'textfield',
    '#title' => 'Etherpad URL',
    '#default_value' => variable_get('etherpad_lite_url', 'http://localhost:9001'),
    '#required' => TRUE,
    '#description' => 'URL to your Etherpad Lite installation. Without trailing slash. e.g. http://localhost:9001',
  );

  $form['etherpad_lite_cookie_domain'] = array(
    '#type' => 'textfield',
    '#title' => 'Cookie domain',
    '#default_value' => variable_get('etherpad_lite_cookie_domain', 'localhost'),
    '#required' => TRUE,
    '#description' => 'Cookie Domain for your Etherpad. Must be writable for Drupal. <strong>Without protocoll.</strong> e.g. localhost',
  );

  $form['etherpad_lite_session_timeout'] = array(
    '#type' => 'textfield',
    '#title' => 'Session timeout',
    '#default_value' => variable_get('etherpad_lite_session_timeout', 60 * 60),
    '#required' => TRUE,
    '#description' => 'Session timeout in seconds. Used in the cookie.',
  );

  return system_settings_form($form);
}

/**
 * Implements hook_field_info().
 */
function etherpad_lite_field_info() {
  return array(
    'etherpad' => array(
      'label' => t('Etherpad'),
      'description' => t('This field stores varchar text in the database.'),
      'instance_settings' => array(
        'type' => 0,
        'text_processing' => 1,
      ),
      'default_widget' => 'etherpad_writer',
      'default_formatter' => 'etherpad_iframe',
    ),
  );
}

/**
 * Implements hook_field_widget_info().
 */
function etherpad_lite_field_widget_info() {
  return array(
    'etherpad_writer' => array(
      'label' => t('Etherpad'),
      'field types' => array('etherpad'),
      'settings' => array('size' => 60),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_DEFAULT,
        'default value' => FIELD_BEHAVIOR_DEFAULT,
      ),
    ),
  );
}

/**
 * Implements hook_field_settings_form().
 */
function etherpad_lite_field_settings_form($field, $instance, $has_data) {
  $settings = $field['settings'];
  $form['type'] = array(
    '#type' => 'select',
    '#title' => 'Pad type',
    '#required' => TRUE,
    '#options' => array(
      '0' => t('Public, everyone can view and edit.'),
      '1' => t('Group pad, granted users can view and edit.'),
    ),
    '#default_value' => isset($settings['type']) ? $settings['type'] : 0,
  );
  return $form;
}

/**
 * Implements hook_field_widget_form().
 */
function etherpad_lite_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  global $user;
  $value = isset($items[$delta]['pid']) ? $items[$delta]['pid'] : NULL;
  $element['#delta'] = $delta;

  $access = array(
    'field' => $field,
    'entity_type' => $element['#entity_type'],
  );
  if (isset($element['#bundle'])) {
    $access['bundle'] = $element['#bundle'];
  }

  if (isset($init) && $init == TRUE) {
    $access += array(
      'entity_op' => 'create',
      'op' => 'create',
    );
  }


  switch ($instance['widget']['type']) {
    case 'etherpad_writer':
      $element['pid'] = array(
        '#type' => 'hidden',
        '#default_value' => $value,
      );
      $element['access'] = array(
        '#type' => 'value',
        '#value' => $access,
      );
      $element['#after_build'][] = 'etherpad_lite_reder_iframe';
      break;
  }

  return $element;
}

function etherpad_lite_reder_iframe($element) {
  $pid = $element['pid']['#value'];
  $access = $element['access']['#value'];
  $field = $element['access']['#value']['field'];

  if ($pid == NULL) {
    $hidePad = TRUE;
    // Create a group pad.
    if ($field['settings']['type'] == 1) {
      $result = etherpad_lite_client()->createGroup();
      if (!empty($result['data']['groupID'])) {
        $gid = $result['data']['groupID'];
        $init = TRUE;
      }
      $result = etherpad_lite_client()->createGroupPad('', uniqid('', TRUE), $gid);
      if (!empty($result['data']['padID'])) {
        $pid = $result['data']['padID'];
      }
    } else {
      // Create a public pad.
      $public_pid = uniqid('', TRUE);
      $result = etherpad_lite_client()->createPad('', $public_pid);
      if ($result['code'] == 0 && $result['message'] == 'ok') {
        $pid = $public_pid;
      }
    }

    $element['pid']['#value'] = $pid;
  }

  $element['pad'] = _etherpad_frame($pid, array(), $access);
  return $element;
}

/**
 * Implements hook_field_is_empty().
 */
function etherpad_lite_field_is_empty($item, $field) {
  return empty($item['pid']);
}

/**
 * Implements hook_field_formatter_info().
 */
function etherpad_lite_field_formatter_info() {
  return array(
    'etherpad_iframe' => array(
      'label' => t('Etherpad: iFrame'),
      'field types' => array('etherpad'),
    ),
    'etherpad_iframe_readonly' => array(
      'label' => t('Etherpad: iFrame, Readonly'),
      'field types' => array('etherpad'),
    ),
  );
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function etherpad_lite_field_formatter_info_alter(&$info) {
  if (isset($info['text_default'])) {
    $info['text_default']['field types'][] = 'etherpad';
  }
}

/**
 * Implements hook_field_formatter_view().
 */
function etherpad_lite_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $settings = $display['settings'];

  $access = array(
    'field' => $field,
    'entity_type' => $entity_type,
    'entity' => $entity,
    'op' => 'view',
    'entity_op' => 'view',
  );

  switch ($display['type']) {
    case 'etherpad_iframe':
      foreach($items as $key => $value) {
        $element[$key] = _etherpad_frame($value['pid'], array(), $access);
      }
      break;
    case 'etherpad_iframe_readonly':
      foreach($items as $key => $value) {
        $result = etherpad_lite_client()->getReadOnlyID($value['pid']);
        if (!empty($result['data']['readOnlyID'])) {
          $element[$key] = _etherpad_frame($result['data']['readOnlyID'], array(), $access);
        }
      }
      break;
  }

  return $element;
}

function _etherpad_frame($pid, $options = array(), $access = array()) {
  global $user;
  $options += array(
    'url' => variable_get('etherpad_lite_url', 'http://localhost:9001'),
  );

  $denied = FALSE;
  $group = explode('$', $pid);
  // The pad is a group pad. Grant access to user.
  if (substr($group[0], 0, 1) == 'g') {
    $denied = TRUE;
    $gid = $group[0];
    $access += array(
      'enity_op' => 'update',
      'op' => 'edit',
      'entity' => NULL,
      'account' => NULL,
    );

    if (entity_access($access['enity_op'], $access['entity_type'], $access['entity'], $access['account']) && field_access($access['op'], $access['field'], $access['entity_type'], $access['entity'], $access['account'])) {
      // Update user.
      $result = etherpad_lite_client()->createAuthorIfNotExistsFor(format_username($user->name), $user->uid);
      if (!empty($result['data']['authorID'])) {
        $aid = $result['data']['authorID'];
      }

      // Grant current user.
      if (isset($gid) && isset($aid)) {
        $timeout = time() + variable_get('etherpad_lite_session_timeout', 60 * 60);
        $access = etherpad_lite_client()->createSession($timeout, $aid, $gid);
        if (!empty($access['data']['sessionID'])) {
          setcookie('sessionID', $access['data']['sessionID'], $timeout, '/', variable_get('etherpad_lite_cookie_domain'));
          $denied = FALSE;
        }
      }
    }
  }

  $element = array();
  if ($denied == FALSE) {
    $element = array(
      '#theme' => 'etherpad',
      '#value' => $pid,
      '#attributes' => array(
        'src' => url($options['url'] . '/p/' . $pid, array('external' => TRUE)),
        'class' => array(
          'etherpad',
        ),
      ),
    );
  }

  return $element;
}

/**
 * Implements hook_field_delete().
 *
 * Delete orphan pads.
 */
function etherpad_lite_field_delete($entity_type, $entity, $field, $instance, $langcode, &$items) {
  list($id, $vid, $bundle) = entity_extract_ids($entity_type, $entity);
  foreach ($items as $delta => $item) {
    $result = etherpad_lite_client()->deletePad($item['pid']);
  }
}

/**
 * Implements hook_element_info().
 */
function etherpad_lite_element_info() {
  $types['etherpad'] = array(
    '#theme' => 'etherpad_iframe',
    '#input' => FALSE,
    '#theme_wrappers' => array('form_element'),
  );
  return $types;
}

/**
 * Implements hook_theme().
 */
function etherpad_lite_theme($existing, $type, $theme, $path) {
  return array(
    'etherpad' => array(
      'render element' => 'element',
    ),
    'etherpad_iframe' => array(
      'render element' => 'element',
    )
  );
}

function theme_etherpad(&$variables) {
  $element = $variables['element'];

  $element[0] = $element;
  $element[0]['#theme'] = 'etherpad_iframe';

  // This wrapper is required to apply CSS styling.
  $output = '';
  $output .= '<div class="etherpad-iframe">';
  $output .= drupal_render_children($element);
  $output .= '</div>';
  return $output;
}

function theme_etherpad_iframe(&$variables) {
  $element = $variables['element'];
  $element['#theme'] = 'html_tag';
  $element['#tag'] = 'iframe';
  return drupal_render($element);
}

function etherpad_lite_client($reset = FALSE) {
  static $service;
  if (!isset($service) || $reset) {
    $service = wsclient_service_load('etherpad_lite');
  }
  return $service;
}

/**
 * Implements hook_user_logout().
 */
function etherpad_lite_user_logout($account) {
  $result = etherpad_lite_client()->createAuthorIfNotExistsFor(format_username($account->name), $account->uid);
  if (!empty($result['data']['authorID'])) {
    $aid = $result['data']['authorID'];
    $sessions = etherpad_lite_client()->listSessionsOfAuthor($aid);
    if (!empty($sessions['data'])) {
      foreach($sessions['data'] as $sid => $session) {
        etherpad_lite_client()->deleteSession($sid);
      }
    }
  }
}
