<?php
/**
 * @file
 * Code for the Etherpad Lite client feature.
 */

function etherpad_lite_client_default_wsclient_service() {
  $default_paramter = array();
  $default_paramter['apikey'] = array(
    'type' => 'hidden',
    'default value' => variable_get('etherpad_lite_apikey'),
  );

  $service = new WSClientServiceDescription();
  $service->name = 'etherpad_lite';
  $service->label = 'Etherad lite';
  $service->url = variable_get('etherpad_lite_url', 'http://localhost:9001') . '/api/1/';
  $service->type = 'rest';

  $operation = array();
  $operation['label'] = 'createGroup';
  $operation['url'] = 'createGroup';
  $operation['parameter'] = $default_paramter;
  $operation['result'] = array('type' => 'text', 'label' => 'Result');
  $service->operations['createGroup'] = $operation;

  $operation = array();
  $operation['label'] = 'createPad';
  $operation['url'] = 'createPad';
  $operation['parameter'] = $default_paramter;
  $operation['parameter'] += array(
    'text' => array(
      'type' => 'text',
    ),
    'padID' => array(
      'type' => 'text',
    ),
  );
  $operation['result'] = array('type' => 'text', 'label' => 'Result');
  $service->operations['createPad'] = $operation;

  $operation = array();
  $operation['label'] = 'createGroupPad';
  $operation['url'] = 'createGroupPad';
  $operation['parameter'] = $default_paramter;
  $operation['parameter'] += array(
    'text' => array(
      'type' => 'text',
    ),
    'padName' => array(
      'type' => 'text',
    ),
    'groupID' => array(
      'type' => 'text',
    ),
  );
  $operation['result'] = array('type' => 'text', 'label' => 'Result');
  $service->operations['createGroupPad'] = $operation;

  $operation = array();
  $operation['label'] = 'createAuthor';
  $operation['url'] = 'createAuthor';
  $operation['parameter'] = $default_paramter;
  $operation['parameter'] += array(
    'name' => array(
      'type' => 'text',
    ),
  );
  $operation['result'] = array('type' => 'text', 'label' => 'Result');
  $service->operations['createAuthor'] = $operation;

  $operation = array();
  $operation['label'] = 'createAuthorIfNotExistsFor';
  $operation['url'] = 'createAuthorIfNotExistsFor';
  $operation['parameter'] = $default_paramter;
  $operation['parameter'] += array(
    'name' => array(
      'type' => 'text',
    ),
    'authorMapper' => array(
      'type' => 'text',
    ),
  );
  $operation['result'] = array('type' => 'text', 'label' => 'Result');
  $service->operations['createAuthorIfNotExistsFor'] = $operation;

  $operation = array();
  $operation['label'] = 'listPads';
  $operation['url'] = 'listPads';
  $operation['parameter'] = $default_paramter;
  $operation['parameter'] += array(
    'groupID' => array(
      'type' => 'text',
    ),
  );
  $operation['result'] = array('type' => 'text', 'label' => 'Result');
  $service->operations['listPads'] = $operation;

  $operation = array();
  $operation['label'] = 'createSession';
  $operation['url'] = 'createSession';
  $operation['parameter'] = $default_paramter;
  $operation['parameter'] += array(
    'validUntil' => array(
      'type' => 'text',
    ),
    'authorID' => array(
      'type' => 'text',
    ),
    'groupID' => array(
      'type' => 'text',
    ),
  );
  $operation['result'] = array('type' => 'text', 'label' => 'Result');
  $service->operations['createSession'] = $operation;

  $operation = array();
  $operation['label'] = 'deleteSession';
  $operation['url'] = 'deleteSession';
  $operation['parameter'] = $default_paramter;
  $operation['parameter'] += array(
    'sessionID' => array(
      'type' => 'text',
    ),
  );
  $operation['result'] = array('type' => 'text', 'label' => 'Result');
  $service->operations['deleteSession'] = $operation;

  $operation = array();
  $operation['label'] = 'listSessionsOfGroup';
  $operation['url'] = 'listSessionsOfGroup';
  $operation['parameter'] = $default_paramter;
  $operation['parameter'] += array(
    'groupID' => array(
      'type' => 'text',
    ),
  );
  $operation['result'] = array('type' => 'text', 'label' => 'Result');
  $service->operations['listSessionsOfGroup'] = $operation;

  $operation = array();
  $operation['label'] = 'listSessionsOfAuthor';
  $operation['url'] = 'listSessionsOfAuthor';
  $operation['parameter'] = $default_paramter;
  $operation['parameter'] += array(
    'authorID' => array(
      'type' => 'text',
    ),
  );
  $operation['result'] = array('type' => 'text', 'label' => 'Result');
  $service->operations['listSessionsOfAuthor'] = $operation;

  $operation = array();
  $operation['label'] = 'deletePad';
  $operation['url'] = 'deletePad';
  $operation['parameter'] = $default_paramter;
  $operation['parameter'] += array(
    'padID' => array(
      'type' => 'text',
    ),
  );
  $operation['result'] = array('type' => 'text', 'label' => 'Result');
  $service->operations['deletePad'] = $operation;

  $operation = array();
  $operation['label'] = 'getText';
  $operation['url'] = 'getText';
  $operation['parameter'] = $default_paramter;
  $operation['parameter'] += array(
    'rev' => array(
      'type' => 'text',
    ),
    'padID' => array(
      'type' => 'text',
    ),
  );
  $operation['result'] = array('type' => 'text', 'label' => 'Result');
  $service->operations['getText'] = $operation;

  $operation = array();
  $operation['label'] = 'setText';
  $operation['url'] = 'setText';
  $operation['parameter'] = $default_paramter;
  $operation['parameter'] += array(
    'text' => array(
      'type' => 'text',
    ),
    'padID' => array(
      'type' => 'text',
    ),
  );
  $operation['result'] = array('type' => 'text', 'label' => 'Result');
  $service->operations['setText'] = $operation;

  $operation = array();
  $operation['label'] = 'getRevisionsCount';
  $operation['url'] = 'getRevisionsCount';
  $operation['parameter'] = $default_paramter;
  $operation['parameter'] += array(
    'padID' => array(
      'type' => 'text',
    ),
  );
  $operation['result'] = array('type' => 'text', 'label' => 'Result');
  $service->operations['getRevisionsCount'] = $operation;

  $services[$service->name] = $service;
  return $services;
}
